
[opener]
edit = [
{ run = '$EDITOR "$@"', block = true, for = "unix" },
{ run = "%EDITOR% %*",  block = true, for = "windows" },
]
open = [
# { run = 'xdg-open "$@"', desc = "Open" , for = "linux"},
{ run = "%EDITOR% %*", desc = "Open" , for = "windows"},
]
